### ISSUE TITLE
Scaleway only permit to add a VC1S server

### ISSUE THREAD

**Issue by lakano** [nanobox-io/nanobox-adapter-libcloud#5]
Hi !

The Scaleway adapter only propose a VC1S server, is it possible to support the others servers please?
Or could you tell me how to help you to add them quickly please?
I don't known if the list is fetched from the ScaleWay API (I don't see any routes on their API for that), or if you have a static JSON file. The static/scaleway.json file seems wrong (there is digitalOcean informations inside it).

By the way, do you support ARM architectures? (ScaleWay have a lot of ARM / ARMv8 servers)
If you need I can create a JSON array list like that:
`{"id": "ARM64-2GB", "ram": 2048, "cpu": 4, "disk": 50, "transfer": 1, "dollars_per_hr": 0, "dollars_per_mo": 0},
`
This could be useful to add the architecture ( ARM, ARMv8, x86 ) inside the JSON file and to view it inside the nanobox.io website.

Regards,

**Comment by danhunsaker** [comment]
It should be listing more than just VC1S. That might be the one we default to, but you should be able to scale to others once your initial server is ready.

The `static/*.json` files are OpenAPI spec files, and describe how to talk to the adapter itself, not what data the adapter will use. That comes from the `libcloud` package, which supports many more adapters than we do at the moment.

As to the ARM systems, we only support x86_64, so listing the ARM servers would be distinctly _un_-helpful. If that ever changes, we'll be certain to unlock support for those systems right away.

**Comment by lakano** [comment]
Thanks for your feedback, I'll try to take one and to scale it to check if there is more servers listed. I close the ticket for now and I'll re-open it if I don't see the list when I scale.
Thank you for your prompt response :)
