### ISSUE TITLE
[question] bare metal vs virtual machines

### ISSUE THREAD

**Issue by lakano** [nanobox-io/nanobox-adapter-libcloud#6]
Hi,

We've read in the « Custom provider » documentation that we can use virtual and bare metal servers.
If we have the choice between 2 machines, one virtual, one bare metal, with the same number of  CPU, RAM and SSD, is there any performances increased with nanobox if we take the bare metal server? (less layer of virtualization) 

Thanks for your time!

**Comment by danhunsaker** [comment]
Possibly, but with most providers the difference will be negligible. The real advantage to bare-metal is that you generally get _considerably more_ resources, and you don't have to worry about over-booked servers and sharing your workload with other apps, even with the providers with fewer resources to spread around.

**Comment by lakano** [comment]
Thank you :)
